baseURL = "https://djtai.github.io/"
languageCode = "en-us"
title = "Hinanao-hu // My Journey"
theme = "cactus"
# copyright = "" # cactus will use title if copyright is not set
# disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 3

[[menu.main]]
name = "Topics"
url = "/tags"
weight = 4

[[menu.main]]
name = "Resources"
url = "/resources"
weight = 5


[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  colortheme = "classic"         # dark, light, white, or classic
  rss = true                   # generate rss feed. default value is false
  googleAnalyticsAsync = false  # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "Håfa adai"
  mainSection = "posts"                       # your main section
  showAllPostsOnHomePage = false              # default
  postsOnHomePage = 5                         # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true                         # show tags overview by default.
  showProjectsList = false                    # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "email"
    link = "David.Taitingfong@pm.me"  # no need for "mailto:" in the head
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/DavidTaitingfong"
  # [[params.social]]
  #   name = "gitlab"
  #   link = "https://gitlab.com/DJTai"
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/_DJTai"
  [[params.social]]
    name = "github"
    link = "https://github.com/DJTai"
